### ISSUE TITLE
@font-face

### ISSUE THREAD

**Issue by im-chang** [pinaska/Instanews-App#2]
I have noticed that you have named both of your @font-face fonts "Open Sans". This could cause confusion as to which font you were intending to use. It would be beneficial to differentiate the two fonts in order to prevent the wrong font to be displayed.

**Comment by pinaska** [comment]
Thanks for the comment. I  thought that the font will be displayed based on the font-style property, but I double check.

**Comment by rcass** [comment]
This is naming both fonts the same is correct @im-chang and @pinaska .

This is done to prevent faux bolding. Basically, the font name will be the same but just change the weight and style properties to matched those font files.

Basically when you are using font-family in the code you will also declare the weight and/or style and it will then find the appropriate files to use. 

See here for more info about this:
https://www.metaltoad.com/blog/how-use-font-face-avoid-faux-italic-and-bold-browser-styles
https://stackoverflow.com/questions/2436749/how-to-add-multiple-font-files-for-the-same-font
