### ISSUE TITLE
Check spelling

### ISSUE THREAD

**Issue by im-chang** [pinaska/Instanews-App#3]
On line 47 of your fail function. Please ensure spelling is correct to prevent the user from being confused when there is no content available. 

.fail(function() {
      $('.story-list').append('<p>Sorry, it appears there is a problem. Try agai later</p>');
    });

**Comment by rcass** [comment]
Good catch @im-chang, just remember to used backticks to reference code or use the permalink feature to link to a certain code block. 

It will make the issue easier to read
