### ISSUE TITLE
Select Bar

### ISSUE THREAD

**Issue by im-chang** [pinaska/Instanews-App#5]
The .select category on line 66 of your css. You can consider setting the background-color: #fff because once in mobile format of the site, the selection bar disappears into the background.
<img width="470" alt="screen shot 2018-05-04 at 10 19 25 am" src="https://user-images.githubusercontent.com/38142960/39641890-aca7904e-4f84-11e8-829a-95b32f9d271e.png">

**Comment by pinaska** [comment]
hi, I do not see this behaviour, but I will change it just in case. Thx

**Comment by rcass** [comment]
Maybe once it is resolved get @im-chang to double check that the issue is resolved on his end 👍
